# Generated by Django 2.1.3 on 2019-08-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('from_user', models.ForeignKey(on_delete=models.CASCADE, related_name='fromid', to='match.UserInfo')),
                ('to_user', models.ForeignKey(on_delete=models.CASCADE, related_name='toid', to='match.UserInfo')),
            ],
        ),
    ]
