# Generated by Django 2.1.3 on 2019-08-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
